import React from 'react';
import { readFileSync } from 'node:fs';
import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it, vi } from 'vitest';
import { ProductResult } from '../client/src/ayrovix/components/ProductResult';
import { ProductCandidates } from '../client/src/ayrovix/components/ProductCandidates';
import { LocaleProvider } from '../client/src/i18n/LocaleContext';
import { normalizeSerpApiMatch, priceCommerceProduct, projectProduct, projectCandidate } from '../src/ayrovix/services/commerceProduct';
import { db } from '../src/server';

const source = (changes: Record<string, unknown> = {}) => ({
  title: 'Documented product', description: 'Detailed merchant description, not generated by AYROVI.',
  brand: 'Merchant Brand', source: 'Merchant Shop', link: 'https://merchant-shop.com/p/model',
  price: { value: 50, currency: 'EUR' }, thumbnail: 'https://cdn.merchant-shop.com/p/front.jpg',
  ...changes,
});
const canonical = (changes: Record<string, unknown> = {}) => priceCommerceProduct(db, normalizeSerpApiMatch(source(changes)));
function render(changes: Record<string, unknown> = {}) {
  const p = canonical(changes);
  const html = renderToStaticMarkup(<LocaleProvider><ProductResult product={projectProduct(p)}
    ordering={false} priceVerified onOrder={vi.fn()} /></LocaleProvider>);
  return { html, product: p };
}

describe('one universal sourced product page', () => {
  it('keeps merchant title, description, rating and URL verbatim rather than category-generated copy', () => {
    const { html } = render({ title: 'Running sneaker from merchant', rating: 4.2, reviews: 18 });
    expect(html).toContain('Running sneaker from merchant');
    expect(html).toContain('Detailed merchant description, not generated by AYROVI.');
    expect(html).toContain('Merchant Shop');
    expect(html).toContain('href="https://merchant-shop.com/p/model"');
    expect(html).toContain('4.2/5');
    expect(html).toContain('(18)');
    expect(html).not.toContain('Stock limité');
    expect(html).not.toContain('Il en reste');
  });

  it('shows a three-decimal AYROVI quote separately from foreign-currency reference and one-time cart delivery', () => {
    const { html, product } = render({ original_price: { value: 90, currency: 'EUR' } });
    expect(html).toContain('Prix AYROVI par article');
    expect(html).toContain('Prix boutique');
    expect(html).toContain('Prix de référence boutique');
    expect(html).toContain('90,00');
    expect(html).toContain('Hors livraison locale éventuelle, calculée une fois au panier.');
    expect(product.pricing.referencePrice).toBe(90);
    expect(product.pricing.ayroviPriceTnd).toBe(product.pricing.unitBreakdown?.totalTND);
    expect(html).not.toContain('Acompte : 20%');
  });

  it('shoes: real pointures and disabled source-declared unavailable size, never invented quantities', () => {
    const { html } = render({ title: 'Chaussures de running', category: 'Shoes', options: [
      { name: 'Size', options: [{ id: 'eu42', label: '42 EU', available: true }, { id: 'eu43', label: '43 EU', available: false }] },
      { name: 'Color', options: ['Black', 'White'] },
    ] });
    expect(html).toContain('Pointure');
    expect(html).toContain('42 EU');
    expect(html).toMatch(/<button[^>]*disabled=""[^>]*>43 EU<\/button>/);
    expect(html).toContain('Couleur');
    expect(html).toContain('Guide des tailles/pointures : consulter la fiche du marchand');
    expect(html).toContain('Choisissez les options requises');
    expect(html).not.toContain('Il en reste');
  });

  it('clothing: a documented size group is rendered; a title saying "one size" does not create an option', () => {
    const shirt = render({ title: 'Merchant shirt', options: [{ name: 'Size', options: ['M', 'L'] }] }).html;
    expect(shirt).toContain('Taille');
    expect(shirt).toContain('>M</button>');
    expect(shirt).toContain('>L</button>');
    const unsourced = render({ title: 'Merchant shirt taille unique' }).html;
    expect(unsourced).not.toContain('ay-product__choices');
    expect(unsourced).not.toContain('>Taille unique</button>');
  });

  it('skincare and cosmetics: Shade and Volume come only from the source, not title-derived sizes or per-100 prices', () => {
    const { html } = render({ title: 'Vitamin serum 50 ml', options: [
      { name: 'Shade', options: ['Soft', 'Deep'] }, { name: 'Volume', options: ['30 ml', '50 ml'] },
    ] });
    expect(html).toContain('Shade');
    expect(html).toContain('Volume');
    expect(html).toContain('>50 ml</button>');
    expect(html).not.toContain('Pointure');
    expect(html).not.toContain('/ 100 ml'); // no unverified unit-price calculation
  });

  it('phones and laptops: independent source groups keep their exact names, not a shoe/clothing template', () => {
    const phone = render({ title: 'Smartphone', options: [
      { name: 'Storage', options: ['128 GB', '256 GB'] }, { name: 'RAM', options: ['8 GB', '12 GB'] },
    ] }).html;
    expect(phone).toContain('Storage'); expect(phone).toContain('RAM');
    expect(phone).toContain('>256 GB</button>');
    const laptop = render({ title: 'Notebook computer', options: [
      { name: 'Processor', options: ['P1', 'P2'] }, { name: 'Memory', options: ['16 GB', '32 GB'] },
    ] }).html;
    expect(laptop).toContain('Processor'); expect(laptop).toContain('Memory');
    expect(laptop).not.toContain('Pointure');
  });

  it('electronics with no variants remain orderable without fake selectors; furniture keeps sourced dimensions', () => {
    const receiver = render({ title: 'AV receiver', options: undefined });
    expect(receiver.product.variants.groups).toHaveLength(0);
    expect(receiver.html).not.toContain('ay-product__choices');
    expect(receiver.html).toMatch(/class="ay-product__buy"(?![^>]*disabled)/);
    const table = render({ title: 'Merchant table', options: [
      { name: 'Dimensions', options: ['120 x 60 cm', '160 x 80 cm'] },
      { name: 'Material', options: ['Oak', 'Pine'] },
    ] }).html;
    expect(table).toContain('Dimensions'); expect(table).toContain('Material');
    expect(table).toContain('>160 x 80 cm</button>');
  });

  it('unpriced source remains visibly unavailable and never displays a calculated TND price', () => {
    const { html, product } = render({ price: undefined });
    expect(product.pricing.ayroviPriceTnd).toBeNull();
    expect(html).toContain('Prix indisponible');
    expect(html).toContain('disabled=""');
    expect(html).not.toContain('0,000 DT');
  });

  it('results and detail project from the same canonical quote, including images and description', () => {
    const product = canonical();
    const list = renderToStaticMarkup(<LocaleProvider><ProductCandidates
      candidates={[projectCandidate(product, 80)]} onChoose={vi.fn()} /></LocaleProvider>);
    const detail = renderToStaticMarkup(<LocaleProvider><ProductResult
      product={projectProduct(product)} ordering={false} onOrder={vi.fn()} /></LocaleProvider>);
    expect(list).toContain('Detailed merchant description');
    expect(detail).toContain('Detailed merchant description');
    expect(list).toContain('cdn.merchant-shop.com');
    expect(detail).toContain('cdn.merchant-shop.com');
    expect(projectCandidate(product, 80).priceTnd).toBe(projectProduct(product).priceTnd);
  });

  it('local delivery and deposit statements come from the cart/policy, not a fixed detail-page calculation', () => {
    const code = readFileSync('client/src/ayrovix/components/ProductResult.tsx', 'utf8');
    expect(code).toContain('useCommercePolicy');
    expect(code).not.toContain('Acompte : 20%');
    expect(code).toContain('validation.price.unitPriceTnd');
    expect(code).toContain('validateProductForCart');
    expect(code).not.toContain('pricePer100(');
    expect(code).not.toContain('classifyProduct(');
  });
});
