/** Actual customer UI + APIs + isolated SQLite. No live account, mail, OAuth or payment service used. */
import { chromium, firefox } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import sharp from 'sharp';
async function run(){
 Object.assign(process.env,{NODE_ENV:'test',DATABASE_PATH:':memory:',CUSTOMER_AUTH_SECRET:'account-browser-test-only-secret-01234567890123456789',ADMIN_EMAIL:'admin@example.com',ADMIN_PASSWORD:'Test-admin-password-123!',MAIL_PROVIDER:'',MAIL_API_KEY:'',MAIL_FROM:'',GOOGLE_CLIENT_ID:'',FACEBOOK_APP_ID:'',APPLE_CLIENT_ID:'',CUSTOMER_OTP_PROVIDER:'console'});
 const {app,db}=await import('../src/server');const server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));const base=`http://127.0.0.1:${(server.address() as any).port}`;
 const browser=await chromium.launch({headless:true});let checks=0;const errors:string[]=[];const check=(v:unknown,m:string)=>{assert.ok(v,m);checks++;};const output='screenshots/account';await mkdir(output,{recursive:true});
 const context=await browser.newContext({viewport:{width:390,height:844},locale:'fr'});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 const password='Original-password-1!';const email='account-demo@example.com';
 const openHome=async()=>{await page.goto(`${base}/?customerAuth=login`);await page.locator('.ac-profile-card').waitFor();await page.locator('.ac-home>.ac-loading').waitFor({state:'hidden'});};
 const section=async(id:string)=>{await page.locator(`[data-account-section="${id}"]`).click();await page.locator('.ac-section>.ac-loading').waitFor({state:'hidden'});};
 const back=async()=>{await page.locator('.ac-header button').click();await page.locator('.ac-home').waitFor();await page.locator('.ac-home>.ac-loading').waitFor({state:'hidden'});};
 const layout=async()=>{check(await page.locator('.customer-account').evaluate(e=>e.scrollWidth<=e.clientWidth),'no outer horizontal overflow');check(await page.locator('.ac-main').evaluate(e=>e.scrollWidth<=e.clientWidth),'no content overflow');};
 try{
  const registered=await context.request.post(`${base}/api/customer/auth/email/register`,{data:{displayName:'Amira Ben Ali',email,password}});check(registered.ok(),'real test account created');const id=(await registered.json()).data.account.id;
  const now=new Date().toISOString();
  db.run("INSERT INTO customer_notifications(id,account_id,type,title,message,created_at) VALUES(?,?,'ACCOUNT',?,?,?)",'account-test-notice',id,'Bienvenue chez AYROVI','Votre compte de démonstration est prêt.',now);
  db.run("INSERT INTO customer_favorites(id,account_id,source_url,title,price_tnd,created_at) VALUES(?,?,?,?,?,?)",'account-test-favorite',id,'https://example.com/product','Article de démonstration',49,now);
  await openHome();check(await page.locator('.ac-profile-card__text').innerText()==='Amira Ben Ali\naccount-demo@example.com','identity from session');check(await page.locator('.ac-menu-row').count()===7,'only grouped functional landing rows');check(Number(await page.locator('[data-account-section=notifications] .ac-badge').innerText())===db.get<any>('SELECT count(*) n FROM customer_notifications WHERE account_id=? AND read_at IS NULL',id).n,'real unread count');await layout();await page.screenshot({path:`${output}/home-fr.png`});
  for(const width of [320,360,390,414,768,1280]){await page.setViewportSize({width,height:844});await layout();check(await page.locator('.ac-menu-row').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().height>=44)),'touch targets at '+width);}await page.setViewportSize({width:390,height:844});
  // Profile persists through a full reload; avatar is a real multipart upload.
  await page.locator('.ac-profile-card').click();await page.locator('#account-display-name').fill('Amira Ben Ali');await page.getByRole('button',{name:'Enregistrer',exact:true}).click();await page.getByRole('status').filter({hasText:'profil'}).waitFor();check(db.get<any>('SELECT display_name FROM customer_accounts WHERE id=?',id).display_name==='Amira Ben Ali','profile saved to SQLite');
  const image=await sharp({create:{width:400,height:300,channels:3,background:'#ff7900'}}).png().toBuffer();await page.locator('input[type=file]').setInputFiles({name:'avatar.png',mimeType:'image/png',buffer:image});await page.getByRole('status').filter({hasText:'Photo enregistrée'}).waitFor();check(db.get<any>('SELECT avatar_source FROM customer_accounts WHERE id=?',id).avatar_source==='custom','avatar saved on server');await page.screenshot({path:`${output}/profile-fr.png`});await openHome();check((await page.locator('.ac-avatar img').getAttribute('src'))?.startsWith('data:image/jpeg'),'photo survives reload');
  await page.locator('.ac-profile-card').click();await page.getByRole('button',{name:'Supprimer',exact:true}).click();await page.getByRole('status').filter({hasText:'Photo supprimée'}).waitFor();check(db.get<any>('SELECT avatar_source FROM customer_accounts WHERE id=?',id).avatar_source==='none','photo removal persisted');await back();
  // Addresses: CRUD and browser history overlay.
  await section('addresses');await page.getByRole('button',{name:'Ajouter une adresse'}).click();const address=page.getByRole('dialog',{name:'Adresse de livraison',exact:true});await address.getByLabel('Destinataire',{exact:true}).fill('Amira Ben Ali');await address.getByLabel('Téléphone',{exact:true}).fill('+216 20123456');await address.getByLabel('Adresse complète',{exact:true}).fill('10 rue de démonstration');await address.getByRole('button',{name:'Enregistrer',exact:true}).click();await address.waitFor({state:'hidden'});await page.getByText('10 rue de démonstration',{exact:false}).waitFor();check(db.get<any>('SELECT COUNT(*) n FROM customer_addresses WHERE account_id=?',id).n===1,'address persisted');
  await page.getByRole('button',{name:'Modifier',exact:true}).click();await address.getByLabel('Libellé',{exact:true}).fill('Bureau');await address.getByRole('button',{name:'Enregistrer',exact:true}).click();await address.waitFor({state:'hidden'});await page.getByText('Bureau',{exact:false}).waitFor();check(db.get<any>('SELECT label FROM customer_addresses WHERE account_id=?',id).label==='Bureau','address edit persisted');await page.screenshot({path:`${output}/addresses-fr.png`});
  await page.getByRole('button',{name:'Ajouter une adresse'}).click();await address.waitFor();await page.goBack();await address.waitFor({state:'hidden'});check(true,'browser back closes address editor');page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Supprimer',exact:true}).click();await page.getByText('Aucune adresse enregistrée',{exact:true}).waitFor();check(db.get<any>('SELECT COUNT(*) n FROM customer_addresses WHERE account_id=?',id).n===0,'address removed');await back();
  // Sub-navigation preserves orders/payment/invoice/tracking and return history.
  await section('orders');check(await page.locator('.ac-order-nav button').count()===4,'all order sections present');await page.getByText('Aucune commande',{exact:true}).waitFor();await page.screenshot({path:`${output}/orders-fr.png`});for(const name of ['Paiements','Factures','Suivi des colis']){await page.locator('.ac-order-nav').getByRole('button',{name,exact:true}).click();await page.locator('.ac-empty').first().waitFor();await layout();}await openHome();
  await section('notifications');await page.getByRole('button',{name:'Tout marquer comme lu'}).click();await page.getByRole('button',{name:'Tout marquer comme lu'}).waitFor({state:'hidden'});check(db.get<any>('SELECT read_at FROM customer_notifications WHERE id=?','account-test-notice').read_at,'notifications marked read');await back();check(await page.locator('[data-account-section=notifications] .ac-badge').count()===0,'badge updated after return');
  await page.locator('.ac-shortcuts').getByRole('button',{name:/Favoris/}).click();await page.getByText('Article de démonstration',{exact:true}).waitFor();await page.getByRole('button',{name:'Retirer'}).click();await page.getByText('Aucun favori',{exact:true}).waitFor();check(db.get<any>('SELECT count(*) n FROM customer_favorites WHERE account_id=?',id).n===0,'favorite deleted');await back();await page.locator('.ac-shortcuts').getByRole('button',{name:/Panier/}).click();await page.locator('.ac-empty').waitFor();check(true,'cart opens actual empty state');await back();
  // Positive cart quantities use the actual server-owned cart, not a local UI counter.
  db.run("INSERT INTO cart_items(id,session_id,account_id,store,source_url,title,source_price,source_currency,price_tnd,quantity,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)",'account-test-cart','fixture-session',id,'OTHER','https://example.com/item','Article de test',10,'TND',10,1,now,now);
  await page.locator('.ac-shortcuts').getByRole('button',{name:/Panier/}).click();await page.getByText('Article de test',{exact:true}).waitFor();await page.getByRole('button',{name:'Augmenter la quantité de Article de test'}).click();await page.locator('.ac-quantity span').filter({hasText:'2'}).waitFor();check(db.get<any>('SELECT quantity FROM cart_items WHERE id=?','account-test-cart').quantity===2,'cart quantity saved to SQLite');await page.screenshot({path:`${output}/cart-fr.png`});await page.getByRole('button',{name:'Diminuer la quantité de Article de test'}).click();await page.locator('.ac-quantity span').filter({hasText:'1'}).waitFor();await page.getByRole('button',{name:'Supprimer Article de test'}).click();await page.getByText('Votre panier est vide',{exact:true}).waitFor();check(!db.get('SELECT id FROM cart_items WHERE id=?','account-test-cart'),'cart item removed on server');await back();
  // Existing real order endpoints, financial details and non-configured payment gates.
  db.run("INSERT INTO customers(id,name,phone,registered_at,updated_at) VALUES(?,?,?,?,?)",'account-test-customer','Amira Ben Ali','+21620123456',now,now);
  db.run("INSERT INTO orders(id,order_number,customer_id,account_id,status,subtotal_tnd,total_tnd,pricing_snapshot,governorate,address,phone,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",'account-test-order','AY-TEST-001','account-test-customer',id,'AWAITING_DEPOSIT',100,100,'{}','Tunis','Adresse de démonstration','+21620123456',now,now);
  await section('orders');await page.getByRole('button',{name:/AY-TEST-001/}).click();await page.getByRole('heading',{name:'Paiement de l’acompte',exact:true}).waitFor();check(await page.getByRole('button',{name:'Payer l’acompte par carte'}).isDisabled(),'unconfigured card gateway remains disabled');check(await page.getByText('Aucune facture émise pour le moment.',{exact:true}).isVisible(),'no invented invoice for order');await page.screenshot({path:`${output}/order-detail-fr.png`});await page.goBack();await page.locator('.ac-order-nav').waitFor();check(await page.getByRole('button',{name:/AY-TEST-001/}).isVisible(),'browser back closes order detail');await back();
  // Stale section responses cannot render orders into security or overwrite its data.
  let release:()=>void=()=>{};const gate=new Promise<void>(resolve=>{release=resolve;});await page.route('**/api/customer/account/orders',async r=>{await gate;await r.continue();});await page.locator('[data-account-section=orders]').click();await page.locator('.ac-section>.ac-loading').waitFor();await page.locator('.ac-header button').click();await page.locator('.ac-home').waitFor();await section('security');release();await page.unrouteAll({behavior:'wait'});await page.locator('#account-new-password').waitFor();check(await page.locator('#account-new-password').isVisible(),'late orders response ignored');await back();
  // Legal destinations are real pages; help links open the actual app tools.
  await section('terms');for(const path of ['/terms.html','/privacy.html'])check((await context.request.get(base+path)).status()===200,'legal page '+path);await back();await section('lensHelp');check(await page.getByRole('button',{name:'Ouvrir AYROVIX Lens'}).count()===1,'real Lens action');check(await page.getByRole('button',{name:'Ouvrir l’assistant'}).count()===1,'real assistant action');await back();
  // Preferences saved server-side, restored independently of local theme cache.
  await section('settings');await page.getByRole('switch',{name:'Mode sombre'}).check();await page.getByLabel('Commandes',{exact:true}).uncheck();await page.getByRole('button',{name:'Enregistrer les préférences'}).click();await page.waitForFunction(()=>document.documentElement.dataset.ayrovixTheme==='dark');check(db.get<any>('SELECT dark_mode,order_updates FROM customer_preferences WHERE account_id=?',id).order_updates===0,'notification preference persisted');await page.screenshot({path:`${output}/preferences-dark-fr.png`});await page.evaluate(()=>localStorage.setItem('ayrovix-theme','light'));await openHome();await page.waitForFunction(()=>document.documentElement.dataset.ayrovixTheme==='dark');await page.screenshot({path:`${output}/home-dark-fr.png`});check(true,'account theme restored from server');
  // Password mismatch, wrong current password, success, renewed CSRF used by next save.
  await section('security');await page.locator('#account-current-password').fill('wrong');await page.locator('#account-new-password').fill('Updated-password-2!');await page.locator('#account-confirm-password').fill('Different-password-2!');await page.getByRole('button',{name:'Modifier le mot de passe',exact:true}).click();await page.getByText('Les mots de passe ne correspondent pas.').waitFor();check(true,'password confirmation validated');await page.locator('#account-confirm-password').fill('Updated-password-2!');await page.getByRole('button',{name:'Modifier le mot de passe',exact:true}).click();await page.getByText('Le mot de passe actuel est incorrect.').waitFor();check(true,'actual password verification');await page.locator('#account-current-password').fill(password);await page.getByRole('button',{name:'Modifier le mot de passe',exact:true}).click();await page.getByRole('status').filter({hasText:'Mot de passe modifié'}).waitFor();check(db.get<any>('SELECT count(*) n FROM customer_sessions WHERE account_id=?',id).n===1,'password change invalidated older sessions');await page.screenshot({path:`${output}/security-fr.png`});await back();await section('settings');await page.getByRole('switch',{name:'Mode sombre'}).uncheck();await page.getByRole('button',{name:'Enregistrer les préférences'}).click();await page.waitForFunction(()=>document.documentElement.dataset.ayrovixTheme==='light');check(true,'new CSRF works after password change');await back();
  // Explicit network failures are errors, not empty states or successful logout.
  await page.route('**/api/customer/account/orders',r=>r.abort());await section('orders');await page.locator('.ac-load-error').waitFor();check(await page.getByText('Aucune commande',{exact:true}).count()===0,'load failure not disguised as no orders');await page.unroute('**/api/customer/account/orders');await page.getByRole('button',{name:'Réessayer',exact:true}).click();await page.getByRole('button',{name:/AY-TEST-001/}).waitFor();check(true,'retry recovers');await back();
  await page.route('**/api/customer/auth/logout',r=>r.abort());await page.getByRole('button',{name:'Se déconnecter',exact:true}).click();await page.locator('.ac-error').waitFor();check(await page.locator('.ac-profile-card').isVisible(),'logout failure keeps account visible');check(db.get<any>('SELECT count(*) n FROM customer_sessions WHERE account_id=?',id).n===1,'logout failure did not revoke server session');await page.unroute('**/api/customer/auth/logout');
  await page.route('**/api/customer/account/overview',r=>r.abort());await openHome();await page.locator('.ac-inline-error').waitFor();check(await page.locator('.ac-badge').count()===0,'unavailable counts hidden');await page.screenshot({path:`${output}/network-error-fr.png`});await page.unroute('**/api/customer/account/overview');await page.getByRole('button',{name:'Réessayer',exact:true}).click();await page.locator('.ac-inline-error').waitFor({state:'hidden'});
  // Arabic/RTL, long identities and narrow screens.
  await page.evaluate(()=>localStorage.setItem('ayrovi.locale.v1','ar'));await openHome();check(await page.locator('.customer-account').getAttribute('dir')==='rtl','RTL account');await page.screenshot({path:`${output}/home-ar.png`});for(const width of [320,360,390,414]){await page.setViewportSize({width,height:844});await layout();}await page.setViewportSize({width:390,height:844});await section('security');await page.locator('#account-new-password').waitFor();await page.screenshot({path:`${output}/security-ar.png`});check(await page.getByRole('heading',{name:'تغيير كلمة المرور',exact:true}).isVisible(),'Arabic security');await back();await section('settings');await page.getByRole('switch',{name:'الوضع الداكن'}).check();await page.getByRole('button',{name:'حفظ التفضيلات'}).click();await page.waitForFunction(()=>document.documentElement.dataset.ayrovixTheme==='dark');await back();await page.screenshot({path:`${output}/home-dark-ar.png`});
  // Actual logout and second identity isolation.
  await page.getByRole('button',{name:'تسجيل الخروج',exact:true}).click();await page.locator('#auth-email').waitFor();check(await page.locator('#auth-email').inputValue()==='','logout returns blank login');check((await context.request.get(`${base}/api/customer/auth/me`)).status()===401,'logout revokes session');
  const other=await context.request.post(`${base}/api/customer/auth/email/register`,{data:{displayName:'حساب ثانٍ للاختبار',email:'account-second@example.com',password}});check(other.ok(),'second account created');await openHome();await page.waitForFunction(()=>document.documentElement.dataset.ayrovixTheme==='light');check(!(await page.locator('.ac-profile-card').innerText()).includes('Amira'),'identity isolated');await section('security');const otherId=(await other.json()).data.account.id;db.run('UPDATE customer_accounts SET password_hash=NULL WHERE id=?',otherId);await back();await section('security');await page.getByText('دخولك مرتبط بمزوّد الحساب',{exact:true}).waitFor();check(await page.locator('#account-new-password').count()===0,'OAuth-only explanation, no fake password form');
  check(errors.length===0,'no browser errors: '+errors.join(';'));
  // Independent Firefox render + browser back.
  const fox=await firefox.launch({headless:true});try{const fc=await fox.newContext({storageState:await context.storageState(),viewport:{width:360,height:800}});const fp=await fc.newPage();fp.on('pageerror',e=>errors.push(e.message));await fp.goto(`${base}/?customerAuth=login`);await fp.locator('.ac-home').waitFor();await fp.locator('[data-account-section=orders]').click();await fp.locator('.ac-empty').waitFor();await fp.goBack();await fp.locator('.ac-home').waitFor();check(await fp.locator('.ac-main').evaluate(e=>e.scrollWidth<=e.clientWidth),'Firefox layout/back');await fp.screenshot({path:`${output}/firefox-ar.png`});}finally{await fox.close();}
  check(errors.length===0,'no errors in either browser');await writeFile(`${output}/results.json`,JSON.stringify({checks,browsers:['Chromium','Firefox'],locales:['fr','ar'],widths:[320,360,390,414,768,1280],errors,fixtures:'isolated SQLite, fictional accounts; external services disabled'},null,2));console.log(`PASS: ${checks} real browser/API/SQLite assertions; no external services used.`);
 }finally{await browser.close();await new Promise<void>(r=>server.close(()=>r()));db.close();}
}
run().catch(e=>{console.error(e);process.exit(1);});
