// GENERATED by npm run design:build. Edit identity.json, not this file.
export const BRAND = {
  "version": "3.0.0",
  "colors": {
    "canvas": "#FFFFFF",
    "surface": "#F5F5F5",
    "ink": "#000000",
    "action": "#000000",
    "actionHover": "#262626",
    "onAction": "#FFFFFF",
    "muted": "#595959",
    "line": "#D9D9D9",
    "accent": "#FF7900",
    "accentText": "#A74700",
    "success": "#236044",
    "danger": "#A52D2D",
    "focus": "#000000",
    "secondary": "#333333"
  },
  "darkColors": {
    "canvas": "#000000",
    "surface": "#171717",
    "ink": "#FFFFFF",
    "action": "#FFFFFF",
    "actionHover": "#E5E5E5",
    "onAction": "#000000",
    "muted": "#BDBDBD",
    "line": "#525252",
    "accent": "#FF7900",
    "accentText": "#FFAE69",
    "success": "#90D6AF",
    "danger": "#FFABAB",
    "focus": "#FFFFFF",
    "secondary": "#E5E5E5"
  },
  "typography": {
    "preset": "ayrovi-a",
    "stack": "'Zalando Sans', 'Noto Sans Arabic', sans-serif",
    "headingWidth": "112.5%",
    "bodyWeight": 400,
    "headingWeight": 500,
    "labelWeight": 700,
    "priceWeight": 400,
    "bodyLineHeight": 1.5,
    "arabicLineHeight": 1.8,
    "letterSpacing": "0em"
  },
  "fonts": [
    {
      "family": "Zalando Sans",
      "file": "/fonts/editorial/zalando-sans.woff2",
      "weight": "200 900",
      "stretch": "75% 125%",
      "style": "normal",
      "role": "latin-ui-and-numbers",
      "license": "/fonts/editorial/zalando-sans-OFL.txt",
      "sha256": "ba6fc11db691debbd271564b194e37d96fab6d3d58c96574c58ce15696196a8f"
    },
    {
      "family": "Noto Sans Arabic",
      "file": "/fonts/editorial/noto-sans-arabic.woff2",
      "weight": "100 900",
      "style": "normal",
      "role": "arabic-ui",
      "license": "/fonts/editorial/noto-sans-arabic-OFL.txt",
      "sha256": "a83d688c5a2bf59b3e912958833780faecf957e4820c547233ff86dc86198e06"
    }
  ]
} as const;
export const FONT_STACK = BRAND.typography.stack;
